= Socrates Of Athens


== Synopsis
*Socrates* (470 – 399 BC) was a Greek philosopher from Athens who is credited as the founder of Western philosophy and as among the first moral philosophers of the ethical tradition of thought. An enigmatic figure, Socrates authored no texts and is known mainly through the posthumous accounts of classical writers, particularly his students Plato and Xenophon. These accounts are written as dialogues, in which Socrates and his interlocutors examine a subject in the style of question and answer; they gave rise to the Socratic dialogue literary genre. Contradictory accounts of Socrates make a reconstruction of his philosophy nearly impossible, a situation known as the Socratic problem. Socrates was a polarizing figure in Athenian society. In 399 BC, he was accused of impiety and corrupting the youth. After a trial that lasted a day, he was sentenced to death. He spent his last day in prison, refusing offers to help him escape.

== Life

=== Early
Socrates was born in 470 or 469 BC to Sophroniscus and Phaenarete, a stoneworker and a midwife, respectively, in the Athenian deme of Alopece; therefore, he was an Athenian citizen, having been born to relatively affluent Athenians. He lived close to his father's relatives and inherited, as was customary, part of his father's estate, securing a life reasonably free of financial concerns. His education followed the laws and customs of Athens. He learned the basic skills of reading and writing and, like most wealthy Athenians, received extra lessons in various other fields such as gymnastics, poetry and music.

=== Journey
He was married twice (which came first is not clear): his marriage to Xanthippe took place when Socrates was in his fifties, and another marriage was with a daughter of Aristides, an Athenian statesman. He had three sons with Xanthippe. Socrates fulfilled his military service during the Peloponnesian War and distinguished himself in three campaigns, according to Plato.

Another incident that reflects Socrates's respect for the law is the arrest of Leon the Salaminian. As Plato describes in his Apology, Socrates and four others were summoned to the Tholos and told by representatives of the Thirty Tyrants (which began ruling in 404 BC) to arrest Leon for execution. Again Socrates was the sole abstainer, choosing to risk the tyrants' wrath and retribution rather than to participate in what he considered to be a crime.

Socrates attracted great interest from the Athenian public and especially the Athenian youth. He was notoriously ugly, having a flat turned-up nose, bulging eyes and a large belly; his friends joked about his appearance. Socrates was indifferent to material pleasures, including his own appearance and personal comfort. He neglected personal hygiene, bathed rarely, walked barefoot, and owned only one ragged coat. He moderated his eating, drinking, and sex, although he did not practice full abstention. Although Socrates was attracted to youth, as was common and accepted in ancient Greece, he resisted his passion for young men because, as Plato describes, he was more interested in educating their souls. Socrates did not seek sex from his disciples, as was often the case between older and younger men in Athens. Politically, he did not take sides in the rivalry between the democrats and the oligarchs in Athens; he criticized both. The character of Socrates as exhibited in Apology, Crito, Phaedo and Symposium concurs with other sources to an extent that gives confidence in Plato's depiction of Socrates in these works as being representative of the real Socrates.

=== Death
Socrates died in Athens in 399 BC after a trial for impiety (asebeia) and the corruption of the young. He spent his last day in prison among friends and followers who offered him a route to escape, which he refused. He died the next morning, in accordance with his sentence, after drinking poison hemlock. According to the Phaedo, his last words were: “Crito, we owe a rooster to Asclepius. Don't forget to pay the debt.”

== Philosophy

A fundamental characteristic of Plato's Socrates is the Socratic method, or the method of refutation (elenchus). It is most prominent in the early works of Plato, such as Apology, Crito, Gorgias, Republic I, and others. The typical elenchus proceeds as follows. Socrates initiates a discussion about a topic with a known expert on the subject, usually in the company of some young men and boys, and by dialogue proves the expert's beliefs and arguments to be contradictory. Socrates initiates the dialogue by asking his interlocutor for a definition of the subject. As he asks more questions, the interlocutor's answers eventually contradict the first definition. The conclusion is that the expert did not really know the definition in the first place. The interlocutor may come up with a different definition. That new definition, in turn, comes under the scrutiny of Socratic questioning. With each round of question and answer, Socrates and his interlocutor hope to approach the truth. More often, they continue to reveal their ignorance. Since the interlocutors' definitions most commonly represent the mainstream opinion on a matter, the discussion places doubt on the common opinion.

Socrates also tests his own opinions through the Socratic method. Thus Socrates does not teach a fixed philosophical doctrine. Rather, he acknowledges his own ignorance while searching for truth with his pupils and interlocutors.

Scholars have questioned the validity and the exact nature of the Socratic method, or indeed if there even was a Socratic method. In 1982, the scholar of ancient philosophy Gregory Vlastos claimed that the Socratic method could not be used to establish the truth or falsehood of a proposition. Rather, Vlastos argued, it was a way to show that an interlocutor's beliefs were inconsistent. There have been two main lines of thought regarding this view, depending on whether it is accepted that Socrates is seeking to prove a claim wrong. According to the first line of thought, known as the constructivist approach, Socrates indeed seeks to refute a claim by this method, and the method helps in reaching affirmative statements. The non-constructivist approach holds that Socrates merely wants to establish the inconsistency between the premises and the conclusion of the initial argument.

=== Socratic ignorance

Plato's Socrates often claims that he is aware of his own lack of knowledge, especially when discussing ethical concepts such as arete (i.e., goodness, courage) since he does not know the nature of such concepts. For example, during his trial, with his life at stake, Socrates says: "I thought Evenus a happy man, if he really possesses this art (technē), and teaches for so moderate a fee. Certainly I would pride and preen myself if I knew (epistamai) these things, but I do not know (epistamai) them, gentlemen". In some of Plato's dialogues, Socrates appears to credit himself with some knowledge, and can even seem strongly opinionated for a man who professes his own ignorance.

=== Socratic irony
There is a widespread assumption that Socrates was an ironist, mostly based on the depiction of Socrates by Plato and Aristotle. Socrates's irony is so subtle and slightly humorous that it often leaves the reader wondering if Socrates is making an intentional pun. Plato's Euthyphro is filled with Socratic irony. The story begins when Socrates is meeting with Euthyphro, a man who has accused his own father of murder. When Socrates first hears the details of the story, he comments, "It is not, I think, any random person who could do this [prosecute one's father] correctly, but surely one who is already far progressed in wisdom". When Euthyphro boasts about his understanding of divinity, Socrates responds that it is "most important that I become your student". Socrates is commonly seen as ironic when using praise to flatter or when addressing his interlocutors.

=== Virtue and knowledge
Socrates's theory of virtue states that all virtues are essentially one, since they are a form of knowledge. For Socrates, the reason a person is not good is because they lack knowledge. Since knowledge is united, virtues are united as well. Another famous dictum—"no one errs willingly"—also derives from this theory. In Protagoras, Socrates argues for the unity of virtues using the example of courage: if someone knows what the relevant danger is, they can undertake a risk. Aristotle comments: " ... Socrates the elder thought that the end of life was knowledge of virtue, and he used to seek for the definition of justice, courage, and each of the parts of virtue, and this was a reasonable approach, since he thought that all virtues were sciences, and that as soon as one knew [for example] justice, he would be just...




== Trial
In 399 BC, Socrates was formally accused of corrupting the minds of the youth of Athens, and for asebeia (impiety), worshipping false gods and failing to worship the gods of Athens. At the trial, Socrates defended himself unsuccessfully. He was found guilty by a majority vote cast by a jury of hundreds of male Athenian citizens and, according to the custom, proposed his own penalty: that he should be given free food and housing by the state for the services he rendered to the city, or alternatively, that he be fined one mina of silver (according to him, all he had). The jurors declined his offer and ordered the death penalty.

Of all the works written about Socrates' trial, only three survive: Plato's Apology, Xenophon's Apology, and Xenophon's Memorabilia.

Socrates was charged in a politically tense climate. In 404 BC, the Athenians had been crushed by Spartans at the decisive naval Battle of Aegospotami, and subsequently, the Spartans laid siege to Athens. They replaced the democratic government with a new, pro-oligarchic government, named the Thirty Tyrants. Because of their tyrannical measures, some Athenians organized to overthrow the Tyrants—and, indeed, they managed to do so briefly—until a Spartan request for aid from the Thirty arrived and a compromise was sought. When the Spartans left again, however, democrats seized the opportunity to kill the oligarchs and reclaim the government of Athens.

The accusations against Socrates were initiated by a poet, Meletus, who asked for the death penalty in accordance with the charge of asebeia. Other accusers were Anytus and Lycon. After a month or two, in late spring or early summer, the trial started and likely went on for most of one day. There were two main sources for the religion-based accusations. First, Socrates had rejected the anthropomorphism of traditional Greek religion by denying that the gods did bad things like humans do. Second, he seemed to believe in a daimonion—an inner voice with, as his accusers suggested, divine origin.

Plato's Apology starts with Socrates answering the various rumours against him that have given rise to the indictment. First, Socrates defends himself against the rumour that he is an atheist naturalist philosopher, as portrayed in Aristophanes's The Clouds; or a sophist. Against the allegations of corrupting the youth, Socrates answers that he has never corrupted anyone intentionally, since corrupting someone would carry the risk of being corrupted back in return, and that would be illogical, since corruption is undesirable. On the second charge, Socrates asks for clarification. Meletus responds by repeating the accusation that Socrates is an atheist. Socrates notes the contradiction between atheism and worshipping false gods. He then claims that he is "God's gift" to the Athenians, since his activities ultimately benefit Athens; thus, in condemning him to death, Athens itself will be the greatest loser. After that, he says that even though no human can reach wisdom, seeking it is the best thing someone can do, implying money and prestige are not as precious as commonly thought.


The Death of Socrates, by Jacques-Louis David (1787). Socrates was visited by friends in his last night in prison. His discussion with them gave rise to Plato's Crito and Phaedo.
Socrates was given the chance to offer alternative punishments for himself after being found guilty. He could have requested permission to flee Athens and live in exile, but he did not do so. According to Xenophon, Socrates made no proposals, while according to Plato he suggested free meals should be provided for him daily in recognition of his worth to Athens or, more in earnest, that a fine should be imposed on him. The jurors favoured the death penalty by making him drink a cup of hemlock (a poisonous liquid). In return, Socrates warned jurors and Athenians that criticism of them by his many disciples was inescapable, unless they became good men. After a delay caused by Athenian religious ceremonies, Socrates spent his last day in prison. His friends visited him and offered him an opportunity to escape, which he declined.

The question of what motivated Athenians to convict Socrates remains controversial among scholars. There are two theories. The first is that Socrates was convicted on religious grounds; the second, that he was accused and convicted for political reasons. Another, more recent, interpretation synthesizes the religious and political theories, arguing that religion and state were not separate in ancient Athens.

The argument for religious persecution is supported by the fact that Plato's and Xenophon's accounts of the trial mostly focus on the charges of impiety. In those accounts, Socrates is portrayed as making no effort to dispute the fact that he did not believe in the Athenian gods. Against this argument stands the fact that many skeptics and atheist philosophers during this time were not prosecuted. According to the argument for political persecution, Socrates was targeted because he was perceived as a threat to democracy. It was true that Socrates did not stand for democracy during the reign of the Thirty Tyrants and that most of his pupils were against the democrats. The case for it being a political persecution is usually challenged by the existence of an amnesty that was granted to Athenian citizens in 403 BC to prevent escalation to civil war after the fall of the Thirty. However, as the text from Socrates's trial and other texts reveal, the accusers could have fuelled their rhetoric using events prior to 403 BC.