= Semester Essay: 9th Grade Spring Semester
CaptainLugaru <72951616+CaptainLugaru@users.noreply.github.com>
v1.0.0, Monday the 5th of May 2025 13:18 EST
:description: Semester accomplishments, learning goals, and learning objectives
:sectnums:
:sectanchors:
:sectlinks:
:icons: font
:tip-caption: 💡️
:note-caption: ℹ️
:important-caption: ❗
:caution-caption: 🔥
:warning-caption: ⚠️
:toc: preamble
:toclevels: 3
:toc-title: GitHub Learning Trail
:keywords: Homeschool Learning Journey
:imagesdir: ./resources/images
ifdef::env-name[:relfilesuffix: .adoc]

I am writing this essay to show what I learned this semester. +

(@rdd13r - point taken for skimping on the essay description.)

== ML: Decision Trees

I learned about decision trees and what they do.
And I made a masterclass to reflect on this.

. link:../../../labs/Google/Decision-Trees-Full-Course/Decision-Trees.ipynb[Decision Trees Notebook] - understanding Decisions Trees: grade A (@rdd13r).


Next I went on too learn about statistics and probability for machine learning.
Some learning courses for these included: https://brilliant.org/?utm_source=search&utm_medium=cpc[Brilliant.org], https://www.khanacademy.org[Khan Academy], 2 courses from Derek Banas: https://www.youtube.com/watch?v=k_FISWJKoFQ[Probability], and
https://www.youtube.com/watch?v=tcusIOfI_GM&t=1ss[Statistics]. +
Last but not least I learned about the Stock market and how to make money from it. Such Ways on learning this are: https://www.youtube.com/@TheSwedishInvestor[The Swedish Investor], https://www.youtube.com/@marktilbury[Mark Tilbury], https://www.youtube.com/@clearvaluetax9382[Clear Value Tax] Along with
https://auth.investopedia.com/realms/investopedia/protocol/openid-connect/auth?client_id=finance-simulator&redirect_uri=https%3A%2F%2Fwww.investopedia.com%2Fsimulator%2Fportfolio&state=04f87af4-dd16-4c64-ab0a-2ab55ae305a3&response_mode=fragment&response_type=code&scope=openid&nonce=59285f60-87cb-4aaa-b7b6-985116a666eb[Investopedia].

Some Classes I missed though this semester are: history, Science And english but these can be made up in the future.


As for next semester, I plan on Learning: +
1. Business and Economics +
2. Expanding Python +
3. Science and History of computers +
4. Mathematics of Algebra +
5. Models of machine learning and Neural Networks +





