= Captain's Saboteurs
Cpt. Lugaru (CaptainLugaru) <72951616+CaptainLugaru@users.noreply.github.com>
v1.1, 2025-02-05


:description: A breakdown of saboteurs, what they are, and how they affect you.
:sectnums:
:sectanchors:
:sectlinks:
:icons: font
:tip-caption: 💡️
:note-caption: ℹ️
:important-caption: ❗
:caution-caption: 🔥
:warning-caption: ⚠️
:toc: preamble
:toclevels: 1
:toc-title: Saboteur Essay and examination
:keywords: Homeschool Learning Journey
:imagesdir: ./images
:labsdir: ./labs
ifdef::env-name[:relfilesuffix: .adoc]

== The Avoider And Restlessness combo

These two saboteurs are the bane of my existence.
They are a deadly combo as they work very closely together to make my life much harder.
The way they work together is that my Restlessness makes it so that I can't wait for anything.
If I have a job, I will most likely decide to do something else or be bored out of my mind if I don't do something.
The Avoider, though, helps by making it so that I don't want to do hard jobs or boring jobs,
but rather redirect my restlessness into less productive tasks, like playing video games.
Even when I'm doing assignments or important things,
*_my Avoider can kick in and tell me to do things like watch YouTube_*.

=== Week Examination

Now, I'm going to look back at the past week and see if I fought my saboteurs and how it went.

==== Trouble 1

Looking back since last Monday, I have been having trouble with my Restlessness, especially with shop.
My dad can't constantly tell me what to do, and I don't know what else to do,
so I get bored and very unproductive, unable to think straight.
But I think I still did well because I managed to achieve a lot in the end.

==== Trouble 2

As for my Avoider, I have been avoiding some tasks here and there and playing instead,
like today when I was on my phone playing rather than cleaning up.
But I still think, overall, it is a weaker saboteur than Restlessness,
though it can still affect my mood for the rest of the day.

==== Overview

Overall, I would say that I'm still severely struggling with these problems,
but I hope in the future I can fight them better.

== Goals

My two main goals are:

=== 1st goal

With Restlessness, I’m going to fight it head-on by making sticky notes with my tasks and doing them as I see fit.
If someone complains, that’s more of their problem.
When I’m doing things such as outlets with my dad, I’ll redirect myself to another task if it’s something my dad can handle himself,
and I’ll step in when I’m needed.

=== 2nd goal

As for the Avoider, my challenge is to push through and finish assignments and other tasks.
I’ll focus on getting challenging or necessary tasks done as soon as I see them.

== Final Grade: 10/10

#A+#

Well done!