= History: The Brief History of Modern Rus
Cpt. Lugaru (CaptainLugaru) <72951616+CaptainLugaru@users.noreply.github.com>
v1.0, Sunday, January 19, 2025
:description: Exploratory research into the history of modern Rus
:sectnums:
:sectanchors:
:sectlinks:
:icons: font
:tip-caption: 💡️
:note-caption: ℹ️
:important-caption: ❗
:caution-caption: 🔥
:warning-caption: ⚠️
:toc: preamble
:toclevels: 1
:toc-title: History of Ukraine as Rus
:keywords: Homeschool Learning Journey
:imagesdir: ./images
:labsdir: ./labs
ifdef::env-name[:relfilesuffix: .adoc]


Ragnar Lothbrok, A legendary figure who's story has been told for 1000 years has been surrounded in myth and legend.
In this essay we will Separate Legend from fact.
It starts with Sigurdr hringr, king of the swedes Who had a bunch of Mistresses and A wife, Queen of the Swedes.
She gave birth to prince Ragnar, unfortunately for ragnar his mother died when he was 15, and his father married a woman who was about his age of ragnar.
He wanted to marry the daughter of the king of Vendel, but there family refused.
So the king of sweden went to war the king of Vendel and won, so to protect there daughter the king ordered his sons to poison her.
When the king who by the way is 60 years old, found the body, he was super pissed. So he burned her body on a boat which is a tradition usually only saved for queens.
But he felt that he lost to much so he got on a ship with the burning girls corpse so he could die with his teenage crush.
Thanks though to ancient runes recently discovered, his last words were to his son, which he pointed too as he was burning on the boat was:
"Follow the path I laid out for you and reach the goal I never could, become the ultimate king son, For it is in your blood."
Now this sets the scene for ragnar, 15 years old and the king of sweden. He led 1 successful raid after another, gaining the trust of his men.
They even believed when he claimed he had odin's blood in him. But sense ragnar has a lot of historic and mythic tales,
according to the historical facts he probably was a Jarl, aka a owner of lands and probably was under King Horik.
But Ragnar otherwise was still a gifted and talented raider, He was a sea king who was a menace to europe and started with raiding Northumbria.
He even killed a king and ransomed the country and told them to pay him tribute to not kill the new king.
Vikings were raiding the south in full force and after king Charlamanges death in 814
the kingdom of frankia was split, and charlamanges son did not wield the same authority.
The empire was filled with infighting and a lack of stability, Everyone laid claim to be king and claimed parts of the empire.
When Ragnar the sea king heard about this, He made west frankia, situated near the water and made it there bullying victim.
For 20 years, As retribution for past attacks by frankia, the vikings attacked with bigger and bigger fleets.
They raided and looted and pushed deeper and deeper inland. The main viking warlord terrorizing them was ragnar.
In these 20 years ragnar was documented by his men, the vikings as more of a legend then a man as there stories are far less down to earth then the franks story.
Now, when ragnar was made the king of sweden, he went to Norway because there king Fro, Killed his uncle so Ragnar saw this as an opportunity to prove himself to his people.
After many battles by ragnar to reach the king of Norway, his men were resting and they were upon a hill. Ragnar looked down to see that the kings army was fighting another force.
When he looked down he saw that the force was mainly woman and that leading them was some sort of warrior goddess.
Ragnar and his men went down to help the woman win the battle, and after so they introduced themselves.
The women name was Lagertha and her woman were prostitutes who after the chaos of Ragnar's attack, Freed themselves and started to fight Fro's men.
In fact, before Fro Stole these lands Lagertha was the ruler of these lands and she just so happened to take ragnar's heart.
After there combined forces dispatched Fro, Ragnar proposed to Lagertha and she accepted. Under the conditions they rule under her land and they were equals.
For 3 years they lived a good life, they had 3 kids and had a happy family until news arrived that ragnars lands were under attack.
He begged for her to join him to take back his lands but she refused to leave. After he successfully got his lands back, he heard the story of the king of YotaLand.
He would Auction off his daughter to any man who solved his problem. Long ago he gifted his daughter a baby snake, but it turned out to be a dragon.
The dragon grew to a massive size and it wrapped itself around her house, trapping her and making sure no one could get to her.
Ragnar knew that he had to slay the dragon once he heard the Jarl's Daughter was hot. So knowing what he had to face, he made shorts out of wolfs hair and covered it in tar and let it froze.
So equipped with his hairy shorts, a spear, and a shield, he went off to slay the dragon.
After a long fight, ragnar dodged and attack a little too late and the dragon bit down on his leg, but as all seemed lost for ragnar, his furry shorts made it so that the dragons teeth could not penetrate ragnars skin, and the tar made the dragons mouth stick shut.
With the opportunity, ragnar took his spear and he killed the dragon. As a reward the Jarl gave his daughter to Ragnar and gave him the name, Ragnar Lothbrok.
Meaning Ragnar, FurryPants. We don't know exactly what happened historically that actually happened on how ragnar married the daughter, but it was not so uncommon for Jarl's to marry off there daughter to others as a reward for doing a Task.
They had 2 sons, but just like there father, the 2 sons lost there mother when they were teenagers. Ragnar heartbroken could not bear to stay in these lands and he left.
Too handle his grief, Ragnar Killed, raided and destroyed villages. One day in norway raiding, Ragnar and his men decided to make some bread to eat.
So his men he sent broke into a nearby farmhouse and they Told the old couple that lived there to start baking them bread, but they were not scared. They told the vikings that they were already at deaths doors and that they would not bake them bread.
But this was all a facade as in that moment there daughter, the most beautiful woman in the lands arrived. The couple was scared of what the vikings would do to her.
The vikings could do nothing but stare at her. They could do nothing but stare and they burnt there bread, After that they went to ragnar and told him what they found.
But she could only go to see ragnar if she could solve this riddle: To come to him neither clothed or unclothed, to come to him neither full, or hungry, to come to him without no one accompanying her but not alone.
She came to him eating an onion, wearing a fish net, and with a dog. He proposed to her but she refused, knowing a womanizer when she sees one she says that after 10 months of raids, if he came back and still loved her then she would marry him.
He went and raided old paris in 845. He arrived to old paris, with 5000 men. Frankia was weak at this time and they knew it. He blitzed Frankia and destroyed many costal villages.
Charle the bald had 2 army's on both sides of the river protecting the heart of france. so ragnar just attacked the smaller army, and all the other army could do was just watch as there men was being slaughtered.
Ragnar took the remaining members of the smaller army and made a bloody ritual with them to odin. Then on easter sunday, further demoralizing frankia he attacked paris, Showing god was not protecting them.
He forced them to pay him 7000 pounds of gold. And then he raided every costal village they had and returned to norway. They got married and She reveled that she was a daughter of a legendary dragon slayer and a valkrie.
They had 4 legendary sons. Ragnar got old and lazy and faded into legends. but he was still alive and wanted to add to his story before he passed and his sons surpassed him.
Ragnar decided to end his days attacking northumbria. where his first raids started. Ragnar and his men raided deep into ireland. But the leader of Northumbria was pretending to lose.
They trapped and surrounded him in ireland and won in a 1 sided battle. They captured him and threw him into a pit of snakes.
This is what he wanted though, so he had his famous death speech as they were preparing to throw him in:"It gladdens me to know that balder's Father makes ready the benches for banquet, soon we shall be drinking ale from the curved horn's, the champion that comes into Odin's dwelling does not lament his death I shall not enter his hall with words of fear upon my lips, the Aesir welcomes me, death comes without lamenting eager am I to depart this Disir Summon me home those who Odin sends for me the valkries from the halls of the lord of the host. gladly I shall drink ale in the high seat with the aesir, the days of my life are ended, and I laugh while I die." His last words were, "if the porkers knew the punishment of the boar pig, Surly they would break into the sty and hasten to loose him from his affliction"
Once they heard the legend, there father, Has died, his sons gathered the largest viking army in history, the great heathen army which would invade England in 865 and they raided. they unleashed absolute violence for the next 14 years. all to avenge ragnar.