= History: Researching connection between Ragnar Lodbrok and Rus
Cpt. Lugaru (CaptainLugaru) <72951616+CaptainLugaru@users.noreply.github.com>
v1.0, Friday, January 24, 2025
:description: Exploratory research into the history of Vikings in Ukraine—Ragnar Lodbrok
:sectnums:
:sectanchors:
:sectlinks:
:icons: font
:tip-caption: 💡️
:note-caption: ℹ️
:important-caption: ❗
:caution-caption: 🔥
:warning-caption: ⚠️
:toc: preamble
:toclevels: 1
:toc-title: History of Ragnar Lodbrok and Rus
:keywords: Homeschool Learning Journey
:imagesdir: ./images
:labsdir: ./labs
ifdef::env-name[:relfilesuffix: .adoc]


Ragnar Lothbrok was a legendary Norse figure who has many sagas.
 While Ragnar and Ukraine are not directly tied to one another there are indirect links between the norse vikings and modern day ukraine.
This is through varangian and kievan Rus. here are all of the possible connections.
1. Varangians and the Kievan Rus'
During the viking age(8th - 11th century) Norse traders, warriors, settlers, known as Varangians, ventured eastward to eastern Europe.
They established trade routes and settlements along rivers like Dnieper and volga.
These varangians were instrumental in the founding of kievan Rus', a federation of Slavic and Norse tribes centered in kyiv.
Ragnars sons like Bjorn Ironside and Ivar the boneless are often tide to stories of viking expansion in those regions.
2. Rurik and the Rurikid Dynasty
A significant connection to kukraine lies in the norse prince Rurik, who is credited with founding the Rurikid Dynasty around 862.
There dynasty ruled the kievan rus for centuries and established Kyyib as a powerful political and cultural center.
Rurik was a Varangian.
Ultimately there are lots of myths and legends of other connections but those seem to be less historical then these answers.
In the end Ragnar had a certain amount of indirect influence to ukraine but they were impacted never the less.