name: "Prune Actions by CLI"
run-name: "Prune Old Action Runs on [${{ github.repository }}] @ ${{ github.ref }} by ${{ github.actor }} with ${{ github.event_name }}"

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
      - '[0-9]*-*'
  pull_request:
    types:
      - opened
      - reopened
      - closed

permissions:
  actions: write
  contents: write

defaults:
  run:
    shell: zsh -l {0}

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-actions-prune"
  cancel-in-progress: true


jobs:

  cleanup-old-action-runs-leaving-one:
    timeout-minutes: 17
    runs-on: self-hosted
    name: "Prune old actions leaving one"

    steps:

      - name: "Checkout repository source code"
        uses: actions/checkout@v4.2.2
        timeout-minutes: 1
        with:
          fetch-depth: 0
          fetch-tags: 'true'

      - name: "Cleanup old action runs leaving the last one for each workflow"
        run: ./util/src/main/sh/clean-runs.sh
        timeout-minutes: 15
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
