name: GitHub Actions Prune
run-name: "Pruned Old Action Runs but ONE on ${{ github.repository }} by ${{ github.actor }} with ${{ github.event_name }} (Attempt ${{ github.run_attempt }})"
#.github/workflows/github-actions-prune.yml

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
      - '[0-9]*-*'
  create:
    branches:
      - '[0-9]*-*'
  pull_request:
    types:
      - opened
      - reopened
      - closed

permissions:
  actions: write
  contents: write

defaults:
  run:
    shell: zsh -l {0}

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-actions-prune"
  cancel-in-progress: true


jobs:

  cleanup-old-action-runs-leaving-one:
    timeout-minutes: 7
    runs-on: [self-hosted, housekeeping]
    name: "Prune old actions leaving one"

    steps:

      - name: "Checkout repository source code"
        uses: actions/checkout@v4.2.2
        timeout-minutes: 1
        with:
          fetch-depth: 0
          fetch-tags: 'true'

      - name: "Cleanup old action runs leaving the last one for each workflow"
        run: ./src/main/sh/clean-runs.sh
        timeout-minutes: 5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
