name: Build on Push
run-name: "Build on Push on ${{ github.repository }} by ${{ github.actor }} with ${{ github.event_name }} (Attempt ${{ github.run_attempt }})"

on:
  push:
    branches:
      - '[0-9]*-*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  contents: read
  actions: read

concurrency:
  group: "${{ github.workflow }}-push"
  cancel-in-progress: true

defaults:
  run:
    shell: zsh -l {0}

jobs:

  build-on-push:
    name: Build project on push for sanity checks
    timeout-minutes: 13
    runs-on: [self-hosted, builder]

    env:
      GH_TOKEN: ${{ github.token }}

    steps:

      - name: Full Checkout
        id: checkout
        uses: actions/checkout@v4.2.2
        timeout-minutes: 1
        with:
          fetch-depth: 0
          fetch-tags: 'true'


      - name: Build and Test
        run: |
          source "$SDKMAN_DIR/bin/sdkman-init.sh" && \
          sdk current
          ./gradlew clean build test --scan
