name: Build on Push
run-name: "Build on Push on ${{ github.repository }} by ${{ github.actor }} with ${{ github.event_name }} (Attempt ${{ github.run_attempt }})"

on:
  pull_request:
    types:
      - opened
      - reopened
      - closed
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

defaults:
  run:
    shell: zsh -l {0}

concurrency:
  group: "${{ github.workflow }}-push"
  cancel-in-progress: true


jobs:

  build-on-push:
    name: Build project on push for sanity checks
    timeout-minutes: 13
    runs-on: [self-hosted, builder]

    env:
      GH_TOKEN: ${{ github.token }}

    steps:

      - name: Full Checkout
        id: checkout
        uses: actions/checkout@v5.0.0
        timeout-minutes: 1
        with:
          fetch-depth: 0
          fetch-tags: 'true'


      - name: Set up Java
        uses: actions/setup-java@v5.0.0
        timeout-minutes: 5
        with:
          distribution: temurin
          java-version: 21


      - name: Build and Test
        timeout-minutes: 5
        run: |
          ./gradlew clean build test dependencyUpdates asciidoctor asciidoctorPdf asciidoctorEpub
          

      - name: Submit Dependency Graph
        uses: gradle/actions/dependency-submission@v4.4.3
        timeout-minutes: 3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-agree: 'yes'
          build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
          dependency-graph: 'generate-submit-and-upload'

