name: GitHub Caches Prune
run-name: "Pruned Old Action Run Caches on ${{ github.repository }} by ${{ github.actor }} with ${{ github.event_name }} (Attempt ${{ github.run_attempt }})"
#.github/workflows/github-cache-prune.yml

on:
  workflow_dispatch:
  create:
    branches:
      - '[0-9]*-*'
  pull_request:
    types:
      - opened
      - reopened

permissions:
  contents: write
  actions: write

defaults:
  run:
    shell: zsh -l {0}

concurrency:
  group: "${{ github.workflow }}-cache"
  cancel-in-progress: true


jobs:

  cleanup-stale-action-caches:
    timeout-minutes: 11
    runs-on: [self-hosted, housekeeping]
    name: "Prune stale caches if used  over GH Services"

    steps:

      - name: "Checkout repository source code"
        uses: actions/checkout@v4.2.2
        timeout-minutes: 1
        with:
          fetch-depth: 0
          fetch-tags: 'true'


      - name: "Install GitHub Actions Cache Extension"
        run: |
          gh extension install actions/gh-actions-cache
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: "Cleanup stale actions caches"
        run: ./src/main/sh/clean-github-cache.sh
        timeout-minutes: 5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Cleanup agent-local Gradle caches"
        run: ./src/main/sh/check-gradle-cache.sh