name: "Greetings and Welcome!"
run-name: "Gervi Herdem Vitr Greeting for ${{ github.actor }} with ${{ github.event_name }}"

on:
  issues:
  workflow_dispatch:
  workflow_call:
    inputs:
      restriction:
        required: true
        type: string


permissions:
  issues: write
  pull-requests: write

concurrency:
  group: "Greeting Group"
  cancel-in-progress: false

jobs:

  first-time-user-greeting:

    name: "Welcoming new contributors!"
    runs-on: self-hosted
    timeout-minutes: 1

    defaults:
      run:
        shell: zsh -l {0}

    steps:

      - name: "Greet first time contributors!"
        uses: actions/first-interaction@1c611a1969b4f85d5dc5bce96a83653f4f06c795
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Dear Contributor, Welcome to Gervi Herdem Vitr! We're happy to have you here! Please let us know if you wish to pair on this issue. Thank you!"
          pr-message: "Dear Contributor, Congratulations on your first Pull Request @ Gervi Herdem Vitr!"
