name: "Greetings and Welcome!"
run-name: "Gervi Herdem Vitr Greeting for ${{ github.actor }} with ${{ github.event_name }}"

on:
  issues:
    types:
      - assigned

permissions:
  issues: write
  pull-requests: write

defaults:
  run:
    shell: zsh -l {0}

concurrency:
  group: "Greeting Group"
  cancel-in-progress: false


jobs:

  first-time-user-greeting:

    name: "Welcoming new contributors!"
    runs-on: [self-hosted, housekeeping]
    timeout-minutes: 1

    steps:

      - name: "Greet first time contributors!"
        uses: actions/first-interaction@v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            💫 Greetings, friend!

            Welcome to Captain's School. 
            If you wish to collaborate or contribute know that you are most welcome. 
            Our principal can be found as `riddler9297` on Discord.

          pr-message: |
            🛠✨ First Pull Request -- Yay!

            Thank you for contributing to Captain's School.
