name: "Label Pull Request"
run-name: "Label Pull Request with IAW Labeling Guidelines examining content by ${{ github.actor }} with ${{ github.event_name }}"
# https://github.com/actions/labeler

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - closed
      - synchronize
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write

defaults:
  run:
    shell: zsh -l {0}

concurrency:
  group: "${{ github.workflow }}-labels"
  cancel-in-progress: true


jobs:
  label-pull-request-iaw-labeling-guidelines:
    timeout-minutes: 3
    runs-on: [self-hosted, housekeeping]
    name: "Label Pull Request with IAW Labeling Guidelines examining content"

    steps:

      - name: "Label Pull Request pushing labels to GitHub Pull Request"
        uses: actions/labeler@v6.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
