name: "Qodana Security Scan"
run-name: "Qodana Security Scan on [${{ github.repository }}] @ ${{ github.ref }} by ${{ github.actor }} with ${{ github.event_name }}"
# https://app.codacy.com/organizations/gh/Gervi-Hera-Vitr/dashboard

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      restriction:
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write
  checks: write
  statuses: write

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-qodana"
  cancel-in-progress: false

defaults:
  run:
    shell: zsh -l {0}


jobs:

  code-security-scan-with-qodana:
    timeout-minutes: 37
    runs-on: self-hosted
    name: "Qodana Security Scan with Publishing"

    steps:

      - name: "Checkout repository source code"
        uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f
        timeout-minutes: 3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis

      - name: "Run Qodana Analysis Action and Report Generation"
        timeout-minutes: 29
        uses: JetBrains/qodana-action@v2024.3
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_503848163 }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  code-security-scan-codeql-postmortem:
    timeout-minutes: 3
    runs-on: self-hosted
    needs: code-security-scan-with-qodana
    name: "Qodana Quality Scan Execution Validation and Recovery"

    steps:

      - name: "ToDo: Qodana Analysis Postmortem"
        run: |
          echo -e "\n\nQodana Analysis Postmortem placeholder.\n\n"
