name: Security Scan by Snyk
run-name: "Executed Security Scan by Snyk on ${{ github.repository }} by ${{ github.actor }} with ${{ github.event_name }} (Attempt ${{ github.run_attempt }})"
#.github/workflows/security-scan-by-snyk.yml
# See der-jynK https://github.com/snyk/actions/tree/master/setup

on:
  workflow_dispatch:
  schedule:
    - cron: '23 17 4 * *'

permissions:
  contents: read
  security-events: write

defaults:
  run:
    shell: bash

concurrency:
  group: "${{ github.workflow }}-snyk"
  cancel-in-progress: true


jobs:

  snyk-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 11

    steps:

      - name: Checkout code
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0


      - name: Setup Java
        uses: actions/setup-java@v5.0.0
        timeout-minutes: 5
        with:
          distribution: temurin
          java-version: 21


      - name: Run Snyk directly from trunk
        timeout-minutes: 5
        uses: snyk/actions/setup@master


      - name: Run Snyk Test App
        timeout-minutes: 9
        run: snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

